name: uniment_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  http: ^1.2.2
  colorize: ^3.0.0
  dart_console: ^4.1.1


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
