# docker-compose.yml
version: '3'
services:
  app:
    image: ssumuss/uniment:latest  # DOCKERHUB_USERNAME 대신 직접 이미지 이름 지정
    ports:
      - "5555:5555"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=your_jwt_secret_key_here
    restart: always