version: '3'
services:
  app:
    build: .
    ports:
      - "5555:5555"
    environment:
      - MONGODB_URI=mongodb+srv://ssumuss:V06NaA9KChDXqhLQ@cluster0.corri.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules